<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active'                => 'Actif',
    'Admin'                 => 'Administrateur',
    'Akcios'                => 'En promotion',
    'Autok ID'              => 'ID de voiture',
    'Autok Kezelese'        => 'Gestion des voitures',
    'Automata'              => 'Automatique',
    'Benzines'              => 'Essence',
    'Create By'             => 'Créé par',
    'Created At'            => 'Créé le',
    'Deleted'               => 'Supprimé',
    'Dízel'                 => 'Diesel',
    'Eladva'                => 'Vendu',
    'Email'                 => 'E-mail',
    'Felhasznaloi Jog'      => 'Droit d\'utilisateur',
    'Felhasznaloi Jogok ID' => 'ID du droit d\'utilisateur',
    'Felhasznaloi Nev'      => 'Nom d\'utilisateur',
    'Felhasznalok'          => 'Utilisateurs',
    'Felhasznalok Szama'    => 'Nombre d\'utilisateurs',
    'Fooldalra'             => 'À la une',
    'Friendly Name'         => 'Nom de l’URL',
    'Gyartasi Ev'           => 'Année de fabrication',
    'Hirdetes Cime'         => 'Titre de l\'annonce',
    'Hirdetes Leirasa'      => 'Description de l\'annonce',
    'ID'                    => 'ID',
    'Idoszak Megnevezes'    => 'Nom de la période',
    'Jarmutipus ID'         => 'Type de véhicule',
    'Jelszo'                => 'Mot de passe',
    'Jogosultsag Neve'      => 'Nom du droit',
    'Kepek Szama'           => 'Nombre d’images',
    'Kezdo Osszeg'          => 'Montant de départ',
    'Kilometer'             => 'Kilométrage',
    'Kisteherautó'          => 'Camionnette',
    'Manuális'              => 'Manuelle',
    'Marka ID'              => 'Marque',
    'Megnevezes'            => 'Désignation',
    'Menu ID'               => 'ID du menu',
    'Menu Name'             => 'Nom du menu',
    'Menu Url'              => 'URL du menu',
    'Model'                 => 'Modèle',
    'Motortipus ID'         => 'Type de moteur',
    'Muszaki Ervenyes'      => 'Contrôle technique valide',
    'Name'                  => 'Nom',
    'Parent ID'             => 'ID parent',
    'Please Select'         => 'Veuillez choisir',
    'Publikalva'            => 'Publié',
    'Sorrend'               => 'Ordre',
    'Szuperadmin'           => 'Super administrateur',
    'Teljesitmeny'          => 'Puissance',
    'Teszt'                 => 'Test',
    'Updated At'            => 'Mis à jour le',
    'Updated By'            => 'Mis à jour par',
    'Valto ID'              => 'Boîte de vitesses',
    'Veg Osszeg'            => 'Montant total',
    'Vetelar'               => 'Prix d\'achat',
    'confirm_text'          => 'Voulez-vous vraiment supprimer l’élément {name} ?',
    'delete_text'           => 'Suppression de {name} réussie !',
    'edit_text'             => 'Modification de {name} réussie !',
    'igen'                  => 'oui',
    'logout'                => 'déconnexion',
    'nem'                   => 'non',
    'save'                  => 'Enregistrer',
    'Adoszam'               => '',
    'Cegnev'                => '',
    'Lakcim'                => '',
    'Nev'                   => '',
    'Szemelyi Szam'         => '',
    'Szuletesi Datum'       => '',
    'Telefon'               => '',
    'Tipus'                 => '',
    'Ugyfel Letrehozasa'    => '',
    'Ugyfelek Kezelese'     => '',
];
