name: PHP Lint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: PHP beállítása
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: PHP Lint futtatása
        run: find . -type f -name "*.php" -exec php -l {} \;
