<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email'                  => 'E-mail',
    'Felhasznaloi Jog'       => 'Felhasználói jog',
    'Felhasznaloi Nev'       => 'Felhasználói név',
    'Felhasznalok'           => 'Felhasználók',
    'Felhasznalok Szama'     => 'Felhasználók száma',
    'Friendly Name'          => 'URL neve',
    'Idoszak Megnevezes'     => 'Megnevezés',
    'Jelszo'                 => 'Jelszó',
    'Jogosultsag Neve'       => 'Jogosultság',
    'Kezdo Osszeg'           => 'Kezdő összeg',
    'Megnevezes'             => 'Megnevezés',
    'Menu Name'              => 'Menü neve',
    'Menu Url'               => 'URL',
    'Name'                   => 'Megnevezés',
    'Parent ID'              => 'Szülő elem',
    'Please Select'          => 'Kérem válasszon',
    'Sorrend'                => 'Sorrend',
    'Veg Osszeg'             => 'Végösszeg',
    'save'                   => 'Mentés',
    'Active'                 => '',
    'Create By'              => '',
    'Created At'             => '',
    'Deleted'                => '',
    'Felhasznaloi Jogok ID'  => '',
    'Gyartasi Ev'            => 'Gyártási év',
    'Hirdetes Cime'          => 'Hirdetés címe',
    'Hirdetes Leirasa'       => 'Hirdetés leírása',
    'ID'                     => '',
    'Jarmutipus ID'          => 'Jármű típusa',
    'Kilometer'              => 'Kilométer',
    'Marka ID'               => 'Márka',
    'Menu ID'                => '',
    'Model'                  => 'Model',
    'Motortipus ID'          => 'Motortípus',
    'Muszaki Ervenyes'       => 'Müszaki érvényes',
    'Teljesitmeny'           => 'Teljesítmény',
    'Updated At'             => '',
    'Updated By'             => '',
    'Valto ID'               => 'Váltó',
    'Vetelar'                => 'Vételár',
    'create_edit_vegzettseg' => '',
    'logout'                 => '',
];
