<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Akcios'                 => 'Akciós',
    'Autok Kezelese'         => 'Autók kezelése',
    'Eladva'                 => 'Eladva',
    'Email'                  => 'E-mail',
    'Felhasznaloi Jog'       => 'Felhasználói jog',
    'Felhasznaloi Nev'       => 'Felhasználói név',
    'Felhasznalok'           => 'Felhasználók',
    'Felhasznalok Szama'     => 'Felhasználók száma',
    'Fooldalra'              => 'Kiemelt',
    'Friendly Name'          => 'URL neve',
    'Gyartasi Ev'            => 'Gyártási év',
    'Hirdetes Cime'          => 'Hirdetés címe',
    'Hirdetes Leirasa'       => 'Hirdetés leírása',
    'Idoszak Megnevezes'     => 'Megnevezés',
    'Jarmutipus ID'          => 'Jármű típusa',
    'Jelszo'                 => 'Jelszó',
    'Jogosultsag Neve'       => 'Jogosultság',
    'Kepek Szama'            => 'Képek száma',
    'Kezdo Osszeg'           => 'Kezdő összeg',
    'Kilometer'              => 'Kilométer',
    'Marka ID'               => 'Márka',
    'Megnevezes'             => 'Megnevezés',
    'Menu Name'              => 'Menü neve',
    'Menu Url'               => 'URL',
    'Model'                  => 'Model',
    'Motortipus ID'          => 'Motortípus',
    'Muszaki Ervenyes'       => 'Müszaki érvényes',
    'Name'                   => 'Megnevezés',
    'Parent ID'              => 'Szülő elem',
    'Please Select'          => 'Kérem válasszon',
    'Publikalva'             => 'Publikálva',
    'Sorrend'                => 'Sorrend',
    'Teljesitmeny'           => 'Teljesítmény',
    'Valto ID'               => 'Váltó',
    'Veg Osszeg'             => 'Végösszeg',
    'Vetelar'                => 'Vételár',
    'confirm_text'           => 'Biztosan törli a(z) {name} elemet!',
    'delete_text'            => '{name} törlése sikeres!',
    'edit_text'              => '{name} szerkesztése sikeres!',
    'save'                   => 'Mentés',
    'Active'                 => '',
    'Admin'                  => '',
    'Adoszam'                => 'Adószám',
    'Autok ID'               => '',
    'Automata'               => '',
    'Benzines'               => '',
    'Cegnev'                 => 'Cégnév',
    'Create By'              => '',
    'Created At'             => '',
    'Deleted'                => '',
    'Dízel'                  => '',
    'Felhasznaloi Jogok ID'  => '',
    'ID'                     => '',
    'Kisteherautó'           => '',
    'Lakcim'                 => 'Lakcím/Cég székhelye',
    'Manuális'               => '',
    'Menu ID'                => '',
    'Nev'                    => 'Név',
    'Szemelyi Szam'          => 'Személyi szám',
    'Szuletesi Datum'        => 'Születési dátum',
    'Szuperadmin'            => '',
    'Telefon'                => 'Telefon',
    'Teszt'                  => '',
    'Tipus'                  => 'Típus',
    'Ugyfel Letrehozasa'     => 'Ügyfél létrehozása',
    'Ugyfelek Kezelese'      => 'Ügyfelek kezelése',
    'Updated At'             => '',
    'Updated By'             => '',
    'igen'                   => 'Igen',
    'logout'                 => 'Kilépés',
    'nem'                    => 'Nem',
    'Ugyfel Mentese Sikeres' => 'Ügyfél: {ugyfel} mentése sikeres!',
];
