<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active'                 => '',
    'Akcios'                 => '',
    'Autok ID'               => '',
    'Create By'              => '',
    'Created At'             => '',
    'Deleted'                => '',
    'Eladva'                 => '',
    'Email'                  => '',
    'Felhasznaloi Jog'       => '',
    'Felhasznaloi Jogok ID'  => '',
    'Felhasznaloi Nev'       => '',
    'Felhasznalok'           => '',
    'Felhasznalok Szama'     => '',
    'Fooldalra'              => '',
    'Friendly Name'          => '',
    'Gyartasi Ev'            => '',
    'Hirdetes Cime'          => '',
    'Hirdetes Leirasa'       => '',
    'ID'                     => '',
    'Idoszak Megnevezes'     => '',
    'Jarmutipus ID'          => '',
    'Jelszo'                 => '',
    'Jogosultsag Neve'       => '',
    'Kepek Szama'            => '',
    'Kezdo Osszeg'           => '',
    'Kilometer'              => '',
    'Marka ID'               => '',
    'Megnevezes'             => '',
    'Menu ID'                => '',
    'Menu Name'              => '',
    'Menu Url'               => '',
    'Model'                  => '',
    'Motortipus ID'          => '',
    'Muszaki Ervenyes'       => '',
    'Name'                   => '',
    'Parent ID'              => '',
    'Please Select'          => '',
    'Publikalva'             => '',
    'Sorrend'                => '',
    'Teljesitmeny'           => '',
    'Updated At'             => '',
    'Updated By'             => '',
    'Valto ID'               => '',
    'Veg Osszeg'             => '',
    'Vetelar'                => '',
    'logout'                 => '',
    'save'                   => '',
    'create_edit_vegzettseg' => '@@@@',
];
