name: PHP Lint

on:
  push:
    branches:
      - 'dev'
      - 'feature/**'
  pull_request:
    branches:
      - 'dev'
      - 'feature/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        # noinspection UndefinedAction
        uses: actions/checkout@v4

      - name: PHP beállítása
        # noinspection UndefinedAction
        uses: shivammathur/setup-php@v2
        with:
          # noinspection UndefinedParamsPresent
          php-version: '8.2'

      - name: PHP Lint futtatása
        run: find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
