name: PHP Lint & Code Style

on:
  push:
    branches:
      - 'dev'
      - 'feature/**'
  pull_request:
    branches:
      - 'dev'
      - 'feature/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        # noinspection UndefinedAction
        uses: actions/checkout@v4

      - name: PHP beállítása
        # noinspection UndefinedAction
        uses: shivammathur/setup-php@v2
        with:
          # noinspection UndefinedParamsPresent
          php-version: '8.2'

      - name: Composer install (dev csomagokkal)
        run: composer install --prefer-dist

      - name: PHP Lint futtatása
        run: find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: PHP-CS-Fixer ellenőrzés
        run: vendor/bin/php-cs-fixer fix --using-cache=no
               - name: Build mappa előkészítése
                 run: |
                   mkdir build
                   rsync -av --exclude=.git --exclude=build ./ ./build/

      - name: Build kicsomagolása ZIP-be
        run: |
          cd build
          zip -r ../build.zip .

      - name: Artifact feltöltése
        # noinspection UndefinedAction
        uses: actions/upload-artifact@v4
        with:
          # noinspection UndefinedParamsPresent
          name: php-build
          # noinspection UndefinedParamsPresent
          path: build.zip